name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your default branch
    paths:
      - 'docs/**'  # Only trigger when there are changes in the docs folder
      - 'mkdocs.yml'  # Also trigger if mkdocs.yml changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material  # Add your MkDocs theme or plugins here

    - name: Build and Deploy if Changes Exist
      run: |
        git diff --quiet docs/ mkdocs.yml || mkdocs gh-deploy --force
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
