# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: AI and Sound Wiki
nav:
  - Home: index.md
  - Current Projects: pages/projects/projects.md
  - Collaborations: pages/collaborations.md
  - Practical Information: pages/practical_info/practical_info.md
  - Staff: pages/staff.md
  - Blog Posts: pages/blogs/blogs.md
  - Tutorials: pages/tutorials/tutorials.md
  - Idea Box: pages/idea_box/idea_box.md
  - Templates: pages/templates/templates.md
theme:
  name: material
  logo: images/AAU_UK_CIRCLE_white_cmyk.svg
  favicon: images/AAU_ORANGE_LYSTONE.ico
  palette:
    scheme: default
    primary: '#211a52'     # Main color
    accent: '#594fbf'      # Accent color
    background: white       # Background color
extra_css:
  - stylesheets/extra.css

